import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from './provider';
import dotenv from 'dotenv';

const inter = Inter({ subsets: ["latin"] });
dotenv.config();


export const metadata: Metadata = {
  title: "Market Marvel",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
        {children}
          </Providers></body>
    </html>
  );
}

